baseURL = "https://redowlphoto.dk/"
languageCode = "en"
title = "RedOwlPhoto"
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Minimalist seascapes from Mariager Fjord, Als Odde and Øster Hurup."
  defaultTheme = "auto"
  author = "RedOwlPhoto"

[menu]
  [[menu.main]]
    name = "Works"
    url = "/works/"
    weight = 10

  [[menu.main]]
    name = "About & Contact"
    url = "/about/"
    weight = 100