baseURL = "https://redowlphoto.dk/"
languageCode = "en"
title = "RedOwlPhoto"
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# --- Taxonomier (tags + farvegrupper til forsiden) ---
[taxonomies]
  tag     = "tags"
  palette = "palette"

[params]
  description  = "Minimalist seascapes from Mariager Fjord, Als Odde and Øster Hurup."
  defaultTheme = "auto"

  # Bruges af Blowfish til SEO/structured data.
  [params.author]
    name = "RedOwlPhoto"

# --- Topmenu ---
[menu]

  [[menu.main]]
    name    = "Works"
    pageRef = "works"
    weight  = 10

  [[menu.main]]
    name    = "Blog"
    pageRef = "blog"
    weight  = 20

  [[menu.main]]
    name    = "About & Contact"
    pageRef = "about"
    weight  = 100

[[params.social]]
  name = "instagram"
  url  = "https://www.instagram.com/redowlphoto/"
