baseURL      = "https://redowlphoto.dk/"
languageCode = "en"
title        = "RedOwlPhoto"
theme        = "blowfish"

# Brug Git til automatisk lastmod + fallback-rækkefølge
enableGitInfo = true
[frontmatter]
  lastmod = ["lastmod", ":git", "date", "publishDate"]

# Sørg for at taxonomy/term-sider rent faktisk bliver genereret
disableKinds = []

[outputs]
home     = ["HTML", "RSS"]
page     = ["HTML"]
section  = ["HTML", "RSS"]
taxonomy = ["HTML", "RSS"]
term     = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# --- Taxonomier ---
[taxonomies]
  category = "categories"
  tag      = "tags"
  palette  = "palette"

# Relateret indhold (brug categories + tags)
[related]
  includeNewer = true
  threshold    = 0
  toLower      = true
  [[related.indices]]
    name   = "categories"
    weight = 100
  [[related.indices]]
    name   = "tags"
    weight = 80

# Top-level author bruges af flere temaer/partials (giver også author.url til schema i <head>)
[author]
  name = "RedOwlPhoto"
  url  = "https://redowlphoto.dk/"

[params]
  description  = "Minimalist seascapes from Mariager Fjord, Als Odde and Øster Hurup."
  defaultTheme = "auto"

  # Blowfish loader disse fra 'assets/css/...'
  customCSS = ["css/custom.css"]

  # Bruges til SEO, footer-ikon/link og som fallback i schema
  [params.author]
    name  = "RedOwlPhoto"
    url   = "https://redowlphoto.dk/"
    links = [
      { instagram = "https://www.instagram.com/redowlphoto/" }
    ]

  # Skjul temaets egen footer-menu (vi viser vores eget ikon/navn)
  [params.footer]
    showMenu = false

# --- Topmenu ---
[menu]
  [[menu.main]]
    name    = "Works"
    pageRef = "works"
    weight  = 10

  [[menu.main]]
    name    = "Blog"
    pageRef = "blog"
    weight  = 20

  [[menu.main]]
    name    = "About & Contact"
    pageRef = "about"
    weight  = 100
