baseURL = "https://redowlphoto.dk/"
languageCode = "en"
title = "RedOwlPhoto"
theme = "blowfish"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# --- Taxonomier ---
[taxonomies]
  tag       = "tags"
  palette   = "palette"
  category  = "categories"


[params]
  description  = "Minimalist seascapes from Mariager Fjord, Als Odde and Øster Hurup."
  defaultTheme = "auto"

  # Bruges af Blowfish til SEO/structured data + sociale links
  [params.author]
    name  = "RedOwlPhoto"
    links = [
      { instagram = "https://www.instagram.com/redowlphoto/" }
    ]

  # (kan være true/false – gør ingen skade hvis du lader den stå)
  [params.footer]
    showMenu = true

# --- Menus (kun topmenu – ingen footer-menu her) ---
[menu]
  [[menu.main]]
    name    = "Works"
    pageRef = "works"
    weight  = 10

  [[menu.main]]
    name    = "Blog"
    pageRef = "blog"
    weight  = 20

  [[menu.main]]
    name    = "About & Contact"
    pageRef = "about"
    weight  = 100
