[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.127.0"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  GIT_SUBMODULE_STRATEGY = "recursive"
