[build]
  publish = "public"
  command = "hugo --gc --minify && bash scripts/indexnow.sh"

[build.environment]
  HUGO_VERSION = "0.148.2"
  HUGO_EXTENDED = "true"
  HUGO_ENV = "production"
  GIT_SUBMODULE_STRATEGY = "recursive"