backend:
  name: git-gateway
  branch: main

site_url: https://redowlphoto.dk
display_url: https://redowlphoto.dk

# Standard upload-sti for alt andet end "works"
media_folder: "static/uploads"
public_folder: "/uploads"
media_folder_relative: true

collections:
  - name: "works"
    label: "Works"
    label_singular: "Work"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/index"          # -> content/works/<slug>/index.md
    editor:
      preview: false

    # Gem assets i samme mappe som indlægget
    media_folder: ""                # upload til content/works/<slug>/
    public_folder: ""               # skriv relative stier i front matter
    preview_path: "works/{{slug}}/"

    fields:
      - { label: "Title",  name: "title", widget: "string" }
      - { label: "Draft",  name: "draft", widget: "boolean", default: false }
      - { label: "Date",   name: "date",  widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Location", name: "location", widget: "string", hint: "e.g. Als Odde, Denmark", required: false }
      - { label: "Caption",  name: "caption", widget: "text", hint: "Short curatorial text", required: false }

      - label: "Cover"
        name: "cover"
        widget: "object"
        collapsed: false
        fields:
          - { label: "Image", name: "image", widget: "image", choose_url: false, allow_multiple: false, required: true }
          - { label: "ALT text", name: "alt", widget: "string", hint: "Still water at Als Odde under blue dawn light", required: false }

      - { label: "Featured on home", name: "featured", widget: "boolean", default: false, hint: "Vis dette værk i forsideslideshowet", required: false }

      # Hentes fra kollektionen "Categories" nedenfor og gemmer slug
      - label: "Categories"
        name: "categories"
        widget: "relation"
        collection: "category_terms"
        search_fields: ["title", "slug"]
        display_fields: ["title"]
        value_field: "slug"
        multiple: true
        hint: "Vælg 0–∞. Vedligeholdes under Collections → Categories."
        required: false

      - label: "Tags"
        name: "tags"
        widget: "list"
        hint: "Optional keywords (e.g. minimalism, long exposure)"
        required: false

      # Body gemmes for SEO, men vises ikke på siden
      - label: "Body"
        name: "body"
        widget: "markdown"
        required: false
        default: |
          <!--more-->

          {{< schema-work >}}

  # --- NY: Redigér kategorier + intro-tekst (120–200 ord) ---
  - name: "category_terms"
    label: "Categories"
    label_singular: "Category"
    folder: "content/categories"
    create: true
    slug: "{{slug}}"
    path: "{{slug}}/_index"         # -> content/categories/<slug>/_index.md
    media_folder: ""
    public_folder: ""
    editor:
      preview: false
    identifier_field: "slug"
    preview_path: "categories/{{slug}}/"
    fields:
      - { label: "Title (shown on page)", name: "title", widget: "string" }
      - { label: "Slug (lowercase-with-dashes)", name: "slug", widget: "string",
          hint: "fx: sea-fjord", pattern: ["^[a-z0-9-]+$", "Use lowercase, digits and dashes only."] }
      - { label: "Intro (shown at top of the category page)", name: "body", widget: "markdown", required: false }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About & Contact"
        name: "about"
        file: "content/about/index.md"
        editor:
          preview: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body",  name: "body",  widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title",        name: "title", widget: "string" }
      - { label: "Publish Date", name: "date",  widget: "datetime", format: "YYYY-MM-DD" }
      - { label: "Body",         name: "body",  widget: "markdown" }
